name: auto-update

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1,5,9,13,17,21 * * *

jobs:
  build:
    name: auto update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate terminal GIF
        uses: liamg/github-profile-terminal-action@main
        with:
          twitter_username: jehmegh
          theme: dark
          token: ${{ secrets.GITHUB_TOKEN }}

    
