name: auto-update

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1,5,9,13,17,21 * * *

jobs:
  build:
    name: auto update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate terminal GIF
        uses: liamg/github-profile-terminal-action@main
        with:
          config_file: terminal.yml
          output_file: os.gif
          twitter_username: jehmegh
          theme: dark
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit os.gif
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add os.gif
          git commit -m "Update os.gif" || exit 0
          git push
